SELECT p.PRODUCT_CODE, SUM(p.PRICE*o.SALES_AMOUNT) as PRICE FROM PRODUCT p
JOIN OFFLINE_SALE o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SUM(p.PRICE*o.SALES_AMOUNT) DESC, p.PRODUCT_CODE