SELECT r.CAR_ID, r.CAR_TYPE, ROUND(r.DAILY_FEE*30*(100-d.DISCOUNT_RATE)/100) AS FEE FROM CAR_RENTAL_COMPANY_CAR r
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON r.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON r.CAR_TYPE = d.CAR_TYPE
WHERE h.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01') AND d.DURATION_TYPE='30일 이상'
GROUP BY r.CAR_ID
HAVING r.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC