SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
                      GROUP BY MEMBER_ID 
                      ORDER BY COUNT(*) DESC
                      LIMIT 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
