SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID IN (SELECT DISTINCT(CAR_ID) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE >= "2022-10-01")
AND CAR_TYPE = "세단"
ORDER BY CAR_ID DESC;
