SELECT CONCAT('/home/grep/src/', CONCAT(F.BOARD_ID, CONCAT('/', CONCAT(F.FILE_ID, CONCAT(F.FILE_NAME, F.FILE_EXT))))) AS 'FILE_PATH' FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;